# Generated by Django 3.1.11 on 2021-05-17 13:21

import core.models.image_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envs', '0001_initial'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=15, unique=True, verbose_name='public_id')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
                ('title', models.CharField(max_length=500, verbose_name='name')),
                ('content', models.FileField(upload_to=core.models.image_models.content_file_name)),
                ('src', models.JSONField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='channels', to='channels.channel')),
                ('kind', models.ForeignKey(limit_choices_to={'envs_type_name': 'content'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kinds', to='envs.attributes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
