# Generated by Django 3.1.11 on 2021-05-17 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEnvs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'env',
                'verbose_name_plural': 'envs',
            },
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
                ('name', models.CharField(max_length=255)),
                ('envs_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_envs', to='envs.typeenvs')),
            ],
            options={
                'verbose_name': 'env',
                'verbose_name_plural': 'envs',
            },
        ),
    ]
